# Generated by Django 4.1.6 on 2023-02-12 11:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRegistrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_field', models.CharField(max_length=255)),
                ('company_address_country', models.CharField(max_length=255)),
                ('company_address_state', models.CharField(max_length=255)),
                ('company_address_city', models.CharField(max_length=255)),
                ('company_phone', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be numerics only', regex='^[0-9]+$')])),
                ('contact_person_phone', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be numerics only', regex='^[0-9]+$')])),
                ('contact_person_address_country', models.CharField(max_length=255)),
                ('contact_person_address_state', models.CharField(max_length=255)),
                ('contact_person_address_city', models.CharField(max_length=255)),
                ('number_of_employees', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
