# Generated by Django 4.1.6 on 2023-02-12 11:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_registrar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualregistrar',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='individualregistrar',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be numerics only', regex='^[0-9]+$')]),
        ),
    ]
