# Generated by Django 4.1.6 on 2023-02-12 14:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('father_name', models.CharField(max_length=50, null=True)),
                ('grand_father_name', models.CharField(max_length=50, null=True)),
                ('DOB', models.DateField(null=True)),
                ('POB', models.CharField(help_text='place of birth', max_length=20, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be numerics only', regex='^[0-9]+$')])),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6, null=True)),
                ('address_country', models.CharField(max_length=50, null=True)),
                ('address_state', models.CharField(max_length=50, null=True)),
                ('address_city', models.CharField(max_length=50, null=True)),
                ('id_card', models.FileField(null=True, upload_to='uploadedId')),
                ('attachement', models.FileField(null=True, upload_to='uploadedAttachements')),
                ('other_notes', models.TextField(max_length=1000, null=True)),
                ('additional_fields', models.TextField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
