# Generated by Django 4.1.6 on 2023-02-12 14:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='POB',
            field=models.CharField(blank=True, help_text='place of birth', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='additional_fields',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='address_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='address_country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='address_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='attachement',
            field=models.FileField(blank=True, null=True, upload_to='uploadedAttachements'),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='father_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='grand_father_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='id_card',
            field=models.FileField(blank=True, null=True, upload_to='uploadedId'),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='other_notes',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be numerics only', regex='^[0-9]+$')]),
        ),
    ]
