# Generated by Django 4.1.6 on 2023-02-12 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registrant', '0002_registrant_email_alter_registrant_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
