# Generated by Django 4.1.6 on 2023-02-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrant', '0003_alter_registrant_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrant',
            name='id_card',
        ),
        migrations.AddField(
            model_name='registrant',
            name='id_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
